os: linux
dist: xenial
sudo: true

language: python

python:
  - "3.6"

addons:
  postgresql: "10"

install: pip install pytest psycopg2

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres

script: 
  - postmaster --version
  - python setup.py install
  - python scripts/conn.py
  - pytest
