os: linux

sudo: required

services:
  - docker
  - postgresql

language: python

addons:
  apt:
    packages:
    # for docs
    - graphviz

install: pip install pytest psycopg2

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres

jobs:
  include:
  - python: "3.6"

script: 
  - python setup.py install
  - python scripts/conn.py
  - pytest


